---
name: Ruby Testing

on:
  push:
    branches:
      - master
      - '*-stable'
  pull_request:

jobs:
  test:
    name: Ruby
    uses: theforeman/actions/.github/workflows/foreman_plugin.yml@v0
    with:
      plugin: foreman_openscap
      foreman_version: refs/pull/10299/head
